export const elements = [
  {
    symbol: "Ac",
    vdw: null,
    empirical: 1.95,
    calculated: null,
    name: "actinium",
    color: "#70ABFA",
    number: 89,
    single: 1.86,
    double: 1.53,
    triple: 1.4,
  },
  {
    symbol: "Ag",
    vdw: 1.72,
    empirical: 1.6,
    calculated: 1.65,
    name: "silver",
    color: "#C0C0C0",
    number: 47,
    single: 1.28,
    double: 1.39,
    triple: 1.37,
  },
  {
    symbol: "Al",
    vdw: 1.84,
    empirical: 1.25,
    calculated: 1.18,
    name: "aluminium",
    color: "#BFA6A6",
    number: 13,
    single: 1.26,
    double: 1.13,
    triple: 1.11,
  },
  {
    symbol: "Am",
    vdw: null,
    empirical: 1.75,
    calculated: null,
    name: "americium",
    color: "#545CF2",
    number: 95,
    single: 1.66,
    double: 1.35,
    triple: null,
  },
  {
    symbol: "Ar",
    vdw: 1.88,
    empirical: 0.71,
    calculated: 0.71,
    name: "argon",
    color: "#80D1E3",
    number: 18,
    single: 0.96,
    double: 1.07,
    triple: 0.96,
  },
  {
    symbol: "As",
    vdw: 1.85,
    empirical: 1.15,
    calculated: 1.14,
    name: "arsenic",
    color: "#BD80E3",
    number: 33,
    single: 1.21,
    double: 1.14,
    triple: 1.06,
  },
  {
    symbol: "At",
    vdw: 2.02,
    empirical: null,
    calculated: 1.27,
    name: "astatine",
    color: "#754F45",
    number: 85,
    single: 1.47,
    double: 1.38,
    triple: 1.38,
  },
  {
    symbol: "Au",
    vdw: 1.66,
    empirical: 1.35,
    calculated: 1.74,
    name: "gold",
    color: "#FFD123",
    number: 79,
    single: 1.24,
    double: 1.21,
    triple: 1.23,
  },
  {
    symbol: "B",
    vdw: 1.92,
    empirical: 0.85,
    calculated: 0.87,
    name: "boron",
    color: "#FFB5B5",
    number: 5,
    single: 0.85,
    double: 0.78,
    triple: 0.73,
  },
  {
    symbol: "Ba",
    vdw: 2.68,
    empirical: 2.15,
    calculated: 2.53,
    name: "barium",
    color: "#00C900",
    number: 56,
    single: 1.96,
    double: 1.61,
    triple: 1.49,
  },
  {
    symbol: "Be",
    vdw: 1.53,
    empirical: 1.05,
    calculated: 1.12,
    name: "beryllium",
    color: "#C2FF00",
    number: 4,
    single: 1.02,
    double: 0.9,
    triple: 0.85,
  },
  {
    symbol: "Bh",
    vdw: null,
    empirical: null,
    calculated: null,
    name: "bohrium",
    color: "#E00038",
    number: 107,
    single: 1.41,
    double: 1.28,
    triple: 1.19,
  },
  {
    symbol: "Bi",
    vdw: 2.07,
    empirical: 1.6,
    calculated: 1.43,
    name: "bismuth",
    color: "#9E4FB5",
    number: 83,
    single: 1.51,
    double: 1.41,
    triple: 1.35,
  },
  {
    symbol: "Bk",
    vdw: null,
    empirical: null,
    calculated: null,
    name: "berkelium",
    color: "#8A4FE3",
    number: 97,
    single: 1.68,
    double: 1.39,
    triple: null,
  },
  {
    symbol: "Br",
    vdw: 1.85,
    empirical: 1.15,
    calculated: 0.94,
    name: "bromine",
    color: "#A62929",
    number: 35,
    single: 1.14,
    double: 1.09,
    triple: 1.1,
  },
  {
    symbol: "C",
    vdw: 1.7,
    empirical: 0.7,
    calculated: 0.67,
    name: "carbon",
    color: "#909090",
    number: 6,
    single: 0.75,
    double: 0.67,
    triple: 0.6,
  },
  {
    symbol: "Ca",
    vdw: 2.31,
    empirical: 1.8,
    calculated: 1.94,
    name: "calcium",
    color: "#3DFF00",
    number: 20,
    single: 1.71,
    double: 1.47,
    triple: 1.33,
  },
  {
    symbol: "Cd",
    vdw: 1.58,
    empirical: 1.55,
    calculated: 1.61,
    name: "cadmium",
    color: "#FFD98F",
    number: 48,
    single: 1.36,
    double: 1.44,
    triple: null,
  },
  {
    symbol: "Ce",
    vdw: null,
    empirical: 1.85,
    calculated: 2.1,
    name: "cerium",
    color: "#FFFFC7",
    number: 58,
    single: 1.63,
    double: 1.37,
    triple: 1.31,
  },
  {
    symbol: "Cf",
    vdw: null,
    empirical: null,
    calculated: null,
    name: "californium",
    color: "#A136D4",
    number: 98,
    single: 1.68,
    double: 1.4,
    triple: null,
  },
  {
    symbol: "Cl",
    vdw: 1.75,
    empirical: 1.0,
    calculated: 0.79,
    name: "chlorine",
    color: "#1FF01F",
    number: 17,
    single: 0.99,
    double: 0.95,
    triple: 0.93,
  },
  {
    symbol: "Cm",
    vdw: null,
    empirical: 1.76,
    calculated: null,
    name: "curium",
    color: "#785CE3",
    number: 96,
    single: 1.66,
    double: 1.36,
    triple: null,
  },
  {
    symbol: "Cn",
    vdw: null,
    empirical: null,
    calculated: null,
    name: "copernicium",
    number: 112,
    single: 1.22,
    double: 1.37,
    triple: 1.3,
  },
  {
    symbol: "Co",
    vdw: null,
    empirical: 1.35,
    calculated: 1.52,
    name: "cobalt",
    color: "#F090A0",
    number: 27,
    single: 1.11,
    double: 1.03,
    triple: 0.96,
  },
  {
    symbol: "Cr",
    vdw: null,
    empirical: 1.4,
    calculated: 1.66,
    name: "chromium",
    color: "#8A99C7",
    number: 24,
    single: 1.22,
    double: 1.11,
    triple: 1.03,
  },
  {
    symbol: "Cs",
    vdw: 3.43,
    empirical: 2.65,
    calculated: 2.98,
    name: "caesium",
    color: "#57178F",
    number: 55,
    single: 2.32,
    double: 2.09,
    triple: null,
  },
  {
    symbol: "Cu",
    vdw: 1.4,
    empirical: 1.35,
    calculated: 1.45,
    name: "copper",
    color: "#C88033",
    number: 29,
    single: 1.12,
    double: 1.15,
    triple: 1.2,
  },
  {
    symbol: "Db",
    vdw: null,
    empirical: null,
    calculated: null,
    name: "dubnium",
    color: "#D1004F",
    number: 105,
    single: 1.49,
    double: 1.36,
    triple: 1.26,
  },
  {
    symbol: "Ds",
    vdw: null,
    empirical: null,
    calculated: null,
    name: "darmstadtium",
    number: 110,
    single: 1.28,
    double: 1.16,
    triple: 1.12,
  },
  {
    symbol: "Dy",
    vdw: null,
    empirical: 1.75,
    calculated: 2.28,
    name: "dysprosium",
    color: "#1FFFC7",
    number: 66,
    single: 1.67,
    double: 1.33,
    triple: null,
  },
  {
    symbol: "Er",
    vdw: null,
    empirical: 1.75,
    calculated: 2.26,
    name: "erbium",
    color: "#00E675",
    number: 68,
    single: 1.65,
    double: 1.33,
    triple: null,
  },
  {
    symbol: "Es",
    vdw: null,
    empirical: null,
    calculated: null,
    name: "einsteinium",
    color: "#B31FD4",
    number: 99,
    single: 1.65,
    double: 1.4,
    triple: null,
  },
  {
    symbol: "Eu",
    vdw: null,
    empirical: 1.85,
    calculated: 2.31,
    name: "europium",
    color: "#61FFC7",
    number: 63,
    single: 1.68,
    double: 1.34,
    triple: null,
  },
  {
    symbol: "F",
    vdw: 1.47,
    empirical: 0.5,
    calculated: 0.42,
    name: "fluorine",
    color: "#90E050",
    number: 9,
    single: 0.64,
    double: 0.59,
    triple: 0.53,
  },
  {
    symbol: "Fe",
    vdw: null,
    empirical: 1.4,
    calculated: 1.56,
    name: "iron",
    color: "#E06633",
    number: 26,
    single: 1.16,
    double: 1.09,
    triple: 1.02,
  },
  {
    symbol: "Fl",
    vdw: null,
    empirical: null,
    calculated: null,
    name: "flerovium",
    number: 114,
    single: 1.43,
    double: null,
    triple: null,
  },
  {
    symbol: "Fm",
    vdw: null,
    empirical: null,
    calculated: null,
    name: "fermium",
    color: "#B31FBA",
    number: 100,
    single: 1.67,
    double: null,
    triple: null,
  },
  {
    symbol: "Fr",
    vdw: 3.48,
    empirical: null,
    calculated: null,
    name: "francium",
    color: "#420066",
    number: 87,
    single: 2.23,
    double: 2.18,
    triple: null,
  },
  {
    symbol: "Ga",
    vdw: 1.87,
    empirical: 1.3,
    calculated: 1.36,
    name: "gallium",
    color: "#C28F8F",
    number: 31,
    single: 1.24,
    double: 1.17,
    triple: 1.21,
  },
  {
    symbol: "Gd",
    vdw: null,
    empirical: 1.8,
    calculated: 2.33,
    name: "gadolinium",
    color: "#45FFC7",
    number: 64,
    single: 1.69,
    double: 1.35,
    triple: 1.32,
  },
  {
    symbol: "Ge",
    vdw: 2.11,
    empirical: 1.25,
    calculated: 1.25,
    name: "germanium",
    color: "#668F8F",
    number: 32,
    single: 1.21,
    double: 1.11,
    triple: 1.14,
  },
  {
    symbol: "H",
    vdw: 1.1,
    empirical: 0.25,
    calculated: 0.53,
    name: "hydrogen",
    color: "#FFFFFF",
    number: 1,
    single: 0.32,
    double: null,
    triple: null,
  },
  {
    symbol: "He",
    vdw: 1.4,
    empirical: 1.2,
    calculated: 0.31,
    name: "helium",
    color: "#D9FFFF",
    number: 2,
    single: 0.46,
    double: null,
    triple: null,
  },
  {
    symbol: "Hf",
    vdw: null,
    empirical: 1.55,
    calculated: 2.08,
    name: "hafnium",
    color: "#4DC2FF",
    number: 72,
    single: 1.52,
    double: 1.28,
    triple: 1.22,
  },
  {
    symbol: "Hg",
    vdw: 1.55,
    empirical: 1.5,
    calculated: 1.71,
    name: "mercury",
    color: "#B8B8D0",
    number: 80,
    single: 1.33,
    double: 1.42,
    triple: null,
  },
  {
    symbol: "Ho",
    vdw: null,
    empirical: 1.75,
    calculated: 2.26,
    name: "holmium",
    color: "#00FF9C",
    number: 67,
    single: 1.66,
    double: 1.33,
    triple: null,
  },
  {
    symbol: "Hs",
    vdw: null,
    empirical: null,
    calculated: null,
    name: "hassium",
    color: "#E6002E",
    number: 108,
    single: 1.34,
    double: 1.25,
    triple: 1.18,
  },
  {
    symbol: "I",
    vdw: 1.98,
    empirical: 1.4,
    calculated: 1.15,
    name: "iodine",
    color: "#940094",
    number: 53,
    single: 1.33,
    double: 1.29,
    triple: 1.25,
  },
  {
    symbol: "In",
    vdw: 1.93,
    empirical: 1.55,
    calculated: 1.56,
    name: "indium",
    color: "#A67573",
    number: 49,
    single: 1.42,
    double: 1.36,
    triple: 1.46,
  },
  {
    symbol: "Ir",
    vdw: null,
    empirical: 1.35,
    calculated: 1.8,
    name: "iridium",
    color: "#175487",
    number: 77,
    single: 1.22,
    double: 1.15,
    triple: 1.07,
  },
  {
    symbol: "K",
    vdw: 2.75,
    empirical: 2.2,
    calculated: 2.43,
    name: "potassium",
    color: "#8F40D4",
    number: 19,
    single: 1.96,
    double: 1.93,
    triple: null,
  },
  {
    symbol: "Kr",
    vdw: 2.02,
    empirical: null,
    calculated: 0.88,
    name: "krypton",
    color: "#5CB8D1",
    number: 36,
    single: 1.17,
    double: 1.21,
    triple: 1.08,
  },
  {
    symbol: "La",
    vdw: null,
    empirical: 1.95,
    calculated: 2.26,
    name: "lanthanum",
    color: "#70D4FF",
    number: 57,
    single: 1.8,
    double: 1.39,
    triple: 1.39,
  },
  {
    symbol: "Li",
    vdw: 1.82,
    empirical: 1.45,
    calculated: 1.67,
    name: "lithium",
    color: "#CC80FF",
    number: 3,
    single: 1.33,
    double: 1.24,
    triple: null,
  },
  {
    symbol: "Lr",
    vdw: null,
    empirical: null,
    calculated: null,
    name: "lawrencium",
    color: "#C70066",
    number: 103,
    single: 1.61,
    double: 1.41,
    triple: null,
  },
  {
    symbol: "Lu",
    vdw: null,
    empirical: 1.75,
    calculated: 2.17,
    name: "lutetium",
    color: "#00AB24",
    number: 71,
    single: 1.62,
    double: 1.31,
    triple: 1.31,
  },
  {
    symbol: "Lv",
    vdw: null,
    empirical: null,
    calculated: null,
    name: "livermorium",
    number: 116,
    single: 1.75,
    double: null,
    triple: null,
  },
  {
    symbol: "Mc",
    vdw: null,
    empirical: null,
    calculated: null,
    name: "moscovium",
    number: 115,
    single: 1.62,
    double: null,
    triple: null,
  },
  {
    symbol: "Md",
    vdw: null,
    empirical: null,
    calculated: null,
    name: "mendelevium",
    color: "#B30DA6",
    number: 101,
    single: 1.73,
    double: 1.39,
    triple: null,
  },
  {
    symbol: "Mg",
    vdw: 1.73,
    empirical: 1.5,
    calculated: 1.45,
    name: "magnesium",
    color: "#8AFF00",
    number: 12,
    single: 1.39,
    double: 1.32,
    triple: 1.27,
  },
  {
    symbol: "Mn",
    vdw: null,
    empirical: 1.4,
    calculated: 1.61,
    name: "manganese",
    color: "#9C7AC7",
    number: 25,
    single: 1.19,
    double: 1.05,
    triple: 1.03,
  },
  {
    symbol: "Mo",
    vdw: null,
    empirical: 1.45,
    calculated: 1.9,
    name: "molybdenum",
    color: "#54B5B5",
    number: 42,
    single: 1.38,
    double: 1.21,
    triple: 1.13,
  },
  {
    symbol: "Mt",
    vdw: null,
    empirical: null,
    calculated: null,
    name: "meitnerium",
    color: "#EB0026",
    number: 109,
    single: 1.29,
    double: 1.25,
    triple: 1.13,
  },
  {
    symbol: "N",
    vdw: 1.55,
    empirical: 0.65,
    calculated: 0.56,
    name: "nitrogen",
    color: "#3050F8",
    number: 7,
    single: 0.71,
    double: 0.6,
    triple: 0.54,
  },
  {
    symbol: "Na",
    vdw: 2.27,
    empirical: 1.8,
    calculated: 1.9,
    name: "sodium",
    color: "#AB5CF2",
    number: 11,
    single: 1.55,
    double: 1.6,
    triple: null,
  },
  {
    symbol: "Nb",
    vdw: null,
    empirical: 1.45,
    calculated: 1.98,
    name: "niobium",
    color: "#73C2C9",
    number: 41,
    single: 1.47,
    double: 1.25,
    triple: 1.16,
  },
  {
    symbol: "Nd",
    vdw: null,
    empirical: 1.85,
    calculated: 2.06,
    name: "neodymium",
    color: "#C7FFC7",
    number: 60,
    single: 1.74,
    double: 1.37,
    triple: null,
  },
  {
    symbol: "Ne",
    vdw: 1.54,
    empirical: 1.6,
    calculated: 0.38,
    name: "neon",
    color: "#B3E3F5",
    number: 10,
    single: 0.67,
    double: 0.96,
    triple: null,
  },
  {
    symbol: "Nh",
    vdw: null,
    empirical: null,
    calculated: null,
    name: "nihonium",
    number: 113,
    single: 1.36,
    double: null,
    triple: null,
  },
  {
    symbol: "Ni",
    vdw: 1.63,
    empirical: 1.35,
    calculated: 1.49,
    name: "nickel",
    color: "#50D050",
    number: 28,
    single: 1.1,
    double: 1.01,
    triple: 1.01,
  },
  {
    symbol: "No",
    vdw: null,
    empirical: null,
    calculated: null,
    name: "nobelium",
    color: "#BD0D87",
    number: 102,
    single: 1.76,
    double: null,
    triple: null,
  },
  {
    symbol: "Np",
    vdw: null,
    empirical: 1.75,
    calculated: null,
    name: "neptunium",
    color: "#0080FF",
    number: 93,
    single: 1.71,
    double: 1.36,
    triple: 1.16,
  },
  {
    symbol: "O",
    vdw: 1.52,
    empirical: 0.6,
    calculated: 0.48,
    name: "oxygen",
    color: "#FF0D0D",
    number: 8,
    single: 0.63,
    double: 0.57,
    triple: 0.53,
  },
  {
    symbol: "Og",
    vdw: null,
    empirical: null,
    calculated: null,
    name: "oganesson",
    number: 118,
    single: 1.57,
    double: null,
    triple: null,
  },
  {
    symbol: "Os",
    vdw: null,
    empirical: 1.3,
    calculated: 1.85,
    name: "osmium",
    color: "#266696",
    number: 76,
    single: 1.29,
    double: 1.16,
    triple: 1.09,
  },
  {
    symbol: "P",
    vdw: 1.8,
    empirical: 1.0,
    calculated: 0.98,
    name: "phosphorus",
    color: "#FF8000",
    number: 15,
    single: 1.11,
    double: 1.02,
    triple: 0.94,
  },
  {
    symbol: "Pa",
    vdw: null,
    empirical: 1.8,
    calculated: null,
    name: "protactinium",
    color: "#00A1FF",
    number: 91,
    single: 1.69,
    double: 1.38,
    triple: 1.29,
  },
  {
    symbol: "Pb",
    vdw: 2.02,
    empirical: 1.8,
    calculated: 1.54,
    name: "lead",
    color: "#575961",
    number: 82,
    single: 1.44,
    double: 1.35,
    triple: 1.37,
  },
  {
    symbol: "Pd",
    vdw: 1.63,
    empirical: 1.4,
    calculated: 1.69,
    name: "palladium",
    color: "#006985",
    number: 46,
    single: 1.2,
    double: 1.17,
    triple: 1.12,
  },
  {
    symbol: "Pm",
    vdw: null,
    empirical: 1.85,
    calculated: 2.05,
    name: "promethium",
    color: "#A3FFC7",
    number: 61,
    single: 1.73,
    double: 1.35,
    triple: null,
  },
  {
    symbol: "Po",
    vdw: 1.97,
    empirical: 1.9,
    calculated: 1.35,
    name: "polonium",
    color: "#AB5C00",
    number: 84,
    single: 1.45,
    double: 1.35,
    triple: 1.29,
  },
  {
    symbol: "Pr",
    vdw: null,
    empirical: 1.85,
    calculated: 2.47,
    name: "praseodymium",
    color: "#D9FFC7",
    number: 59,
    single: 1.76,
    double: 1.38,
    triple: 1.28,
  },
  {
    symbol: "Pt",
    vdw: 1.75,
    empirical: 1.35,
    calculated: 1.77,
    name: "platinum",
    color: "#D0D0E0",
    number: 78,
    single: 1.23,
    double: 1.12,
    triple: 1.1,
  },
  {
    symbol: "Pu",
    vdw: null,
    empirical: 1.75,
    calculated: null,
    name: "plutonium",
    color: "#006BFF",
    number: 94,
    single: 1.72,
    double: 1.35,
    triple: null,
  },
  {
    symbol: "Ra",
    vdw: 2.83,
    empirical: 2.15,
    calculated: null,
    name: "radium",
    color: "#007D00",
    number: 88,
    single: 2.01,
    double: 1.73,
    triple: 1.59,
  },
  {
    symbol: "Rb",
    vdw: 3.03,
    empirical: 2.35,
    calculated: 2.65,
    name: "rubidium",
    color: "#702EB0",
    number: 37,
    single: 2.1,
    double: 2.02,
    triple: null,
  },
  {
    symbol: "Re",
    vdw: null,
    empirical: 1.35,
    calculated: 1.88,
    name: "rhenium",
    color: "#267DAB",
    number: 75,
    single: 1.31,
    double: 1.19,
    triple: 1.1,
  },
  {
    symbol: "Rf",
    vdw: null,
    empirical: null,
    calculated: null,
    name: "rutherfordium",
    color: "#CC0059",
    number: 104,
    single: 1.57,
    double: 1.4,
    triple: 1.31,
  },
  {
    symbol: "Rg",
    vdw: null,
    empirical: null,
    calculated: null,
    name: "roentgenium",
    number: 111,
    single: 1.21,
    double: 1.16,
    triple: 1.18,
  },
  {
    symbol: "Rh",
    vdw: null,
    empirical: 1.35,
    calculated: 1.73,
    name: "rhodium",
    color: "#0A7D8C",
    number: 45,
    single: 1.25,
    double: 1.1,
    triple: 1.06,
  },
  {
    symbol: "Rn",
    vdw: 2.2,
    empirical: null,
    calculated: 1.2,
    name: "radon",
    color: "#428296",
    number: 86,
    single: 1.42,
    double: 1.45,
    triple: 1.33,
  },
  {
    symbol: "Ru",
    vdw: null,
    empirical: 1.3,
    calculated: 1.78,
    name: "ruthenium",
    color: "#248F8F",
    number: 44,
    single: 1.25,
    double: 1.14,
    triple: 1.03,
  },
  {
    symbol: "S",
    vdw: 1.8,
    empirical: 1.0,
    calculated: 0.88,
    name: "sulfur",
    color: "#FFFF30",
    number: 16,
    single: 1.03,
    double: 0.94,
    triple: 0.95,
  },
  {
    symbol: "Sb",
    vdw: 2.06,
    empirical: 1.45,
    calculated: 1.33,
    name: "antimony",
    color: "#9E63B5",
    number: 51,
    single: 1.4,
    double: 1.33,
    triple: 1.27,
  },
  {
    symbol: "Sc",
    vdw: 2.11,
    empirical: 1.6,
    calculated: 1.84,
    name: "scandium",
    color: "#E6E6E6",
    number: 21,
    single: 1.48,
    double: 1.16,
    triple: 1.14,
  },
  {
    symbol: "Se",
    vdw: 1.9,
    empirical: 1.15,
    calculated: 1.03,
    name: "selenium",
    color: "#FFA100",
    number: 34,
    single: 1.16,
    double: 1.07,
    triple: 1.07,
  },
  {
    symbol: "Sg",
    vdw: null,
    empirical: null,
    calculated: null,
    name: "seaborgium",
    color: "#D90045",
    number: 106,
    single: 1.43,
    double: 1.28,
    triple: 1.21,
  },
  {
    symbol: "Si",
    vdw: 2.1,
    empirical: 1.1,
    calculated: 1.11,
    name: "silicon",
    color: "#F0C8A0",
    number: 14,
    single: 1.16,
    double: 1.07,
    triple: 1.02,
  },
  {
    symbol: "Sm",
    vdw: null,
    empirical: 1.85,
    calculated: 2.38,
    name: "samarium",
    color: "#8FFFC7",
    number: 62,
    single: 1.72,
    double: 1.34,
    triple: null,
  },
  {
    symbol: "Sn",
    vdw: 2.17,
    empirical: 1.45,
    calculated: 1.45,
    name: "tin",
    color: "#668080",
    number: 50,
    single: 1.4,
    double: 1.3,
    triple: 1.32,
  },
  {
    symbol: "Sr",
    vdw: 2.49,
    empirical: 2.0,
    calculated: 2.19,
    name: "strontium",
    color: "#00FF00",
    number: 38,
    single: 1.85,
    double: 1.57,
    triple: 1.39,
  },
  {
    symbol: "Ta",
    vdw: null,
    empirical: 1.45,
    calculated: 2.0,
    name: "tantalum",
    color: "#4DA6FF",
    number: 73,
    single: 1.46,
    double: 1.26,
    triple: 1.19,
  },
  {
    symbol: "Tb",
    vdw: null,
    empirical: 1.75,
    calculated: 2.25,
    name: "terbium",
    color: "#30FFC7",
    number: 65,
    single: 1.68,
    double: 1.35,
    triple: null,
  },
  {
    symbol: "Tc",
    vdw: null,
    empirical: 1.35,
    calculated: 1.83,
    name: "technetium",
    color: "#3B9E9E",
    number: 43,
    single: 1.28,
    double: 1.2,
    triple: 1.1,
  },
  {
    symbol: "Te",
    vdw: 2.06,
    empirical: 1.4,
    calculated: 1.23,
    name: "tellurium",
    color: "#D47A00",
    number: 52,
    single: 1.36,
    double: 1.28,
    triple: 1.21,
  },
  {
    symbol: "Th",
    vdw: null,
    empirical: 1.8,
    calculated: null,
    name: "thorium",
    color: "#00BAFF",
    number: 90,
    single: 1.75,
    double: 1.43,
    triple: 1.36,
  },
  {
    symbol: "Ti",
    vdw: null,
    empirical: 1.4,
    calculated: 1.76,
    name: "titanium",
    color: "#BFC2C7",
    number: 22,
    single: 1.36,
    double: 1.17,
    triple: 1.08,
  },
  {
    symbol: "Tl",
    vdw: 1.96,
    empirical: 1.9,
    calculated: 1.56,
    name: "thallium",
    color: "#A6544D",
    number: 81,
    single: 1.44,
    double: 1.42,
    triple: 1.5,
  },
  {
    symbol: "Tm",
    vdw: null,
    empirical: 1.75,
    calculated: 2.22,
    name: "thulium",
    color: "#00D452",
    number: 69,
    single: 1.64,
    double: 1.31,
    triple: null,
  },
  {
    symbol: "Ts",
    vdw: null,
    empirical: null,
    calculated: null,
    name: "tennessine",
    number: 117,
    single: 1.65,
    double: null,
    triple: null,
  },
  {
    symbol: "U",
    vdw: 1.86,
    empirical: 1.75,
    calculated: null,
    name: "uranium",
    color: "#008FFF",
    number: 92,
    single: 1.7,
    double: 1.34,
    triple: 1.18,
  },
  {
    symbol: "V",
    vdw: null,
    empirical: 1.35,
    calculated: 1.71,
    name: "vanadium",
    color: "#A6A6AB",
    number: 23,
    single: 1.34,
    double: 1.12,
    triple: 1.06,
  },
  {
    symbol: "W",
    vdw: null,
    empirical: 1.35,
    calculated: 1.93,
    name: "tungsten",
    color: "#2194D6",
    number: 74,
    single: 1.37,
    double: 1.2,
    triple: 1.15,
  },
  {
    symbol: "Xe",
    vdw: 2.16,
    empirical: null,
    calculated: 1.08,
    name: "xenon",
    color: "#429EB0",
    number: 54,
    single: 1.31,
    double: 1.35,
    triple: 1.22,
  },
  {
    symbol: "Y",
    vdw: null,
    empirical: 1.8,
    calculated: 2.12,
    name: "yttrium",
    color: "#94FFFF",
    number: 39,
    single: 1.63,
    double: 1.3,
    triple: 1.24,
  },
  {
    symbol: "Yb",
    vdw: null,
    empirical: 1.75,
    calculated: 2.22,
    name: "ytterbium",
    color: "#00BF38",
    number: 70,
    single: 1.7,
    double: 1.29,
    triple: null,
  },
  {
    symbol: "Zn",
    vdw: 1.39,
    empirical: 1.35,
    calculated: 1.42,
    name: "zinc",
    color: "#7D80B0",
    number: 30,
    single: 1.18,
    double: 1.2,
    triple: null,
  },
  {
    symbol: "Zr",
    vdw: null,
    empirical: 1.55,
    calculated: 2.06,
    name: "zirconium",
    color: "#94E0E0",
    number: 40,
    single: 1.54,
    double: 1.27,
    triple: 1.21,
  },
];

export function getVdwRadius(symbol: string): number {
  const element = elements.find((e) => e.symbol === symbol);
  return element?.vdw ?? 1.5;
}

export function getColor(symbol: string): string {
  const element = elements.find((e) => e.symbol === symbol);
  return element?.color ?? "#cccccc";
}

export function getRadius(
  symbol: string,
  type: "vdw" | "empirical" | "calculated" | "single" | "double" | "triple",
): number | null {
  const element = elements.find((e) => e.symbol === symbol);
  if (!element) return null;
  return element[type] ?? null;
}
